### Delete Administrator
DELETE http://localhost:5000/admin/680a13ae9004952cd7d99214
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODBiYWZkYWY2MjFiYWFkMzBkMDI4YTIiLCJ1c2VyUm9sZSI6IkFETUlOSVNUUkFUT1IiLCJpYXQiOjE3NDU1OTY2MzMsImV4cCI6MTc0NjIwMTQzM30.-dHVf3ClZ4MzIbpqu2iOTrvtglUfIArzX-F5i2d9698
Content-Type: application/json



# {
#   "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODBiYWZkYWY2MjFiYWFkMzBkMDI4YTIiLCJ1c2VyUm9sZSI6IkFETUlOSVNUUkFUT1IiLCJpYXQiOjE3NDU1OTY2MzMsImV4cCI6MTc0NjIwMTQzM30.-dHVf3ClZ4MzIbpqu2iOTrvtglUfIArzX-F5i2d9698",
#   "type": "ADMINISTRATOR",
#   "userId": "680bafdaf621baad30d028a2"
# }