### List All Admins
GET http://localhost:5000/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODBhMTNhZTkwMDQ5NTJjZDdkOTkyMTQiLCJ1c2VyUm9sZSI6IkFETUlOSVNUUkFUT1IiLCJpYXQiOjE3NDU1OTQ5MzYsImV4cCI6MTc0NjE5OTczNn0.k0gGlRe-AwZa-dG3f8ZHuZYvYDuJUUGdegc05momRnI
Content-Type: application/json